# Generated by Django 3.1.1 on 2020-09-15 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_username', models.CharField(max_length=255, unique=True)),
                ('profile_metrics', models.TextField(null=True)),
                ('profile_interests', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileStats',
            fields=[
                ('profile_stats_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_name', models.CharField(blank=True, max_length=255)),
                ('profile_bio', models.TextField(blank=True)),
                ('profile_website', models.TextField(blank=True)),
                ('profile_business_category', models.CharField(blank=True, max_length=255)),
                ('profile_is_verified', models.IntegerField(choices=[(0, 'unverified'), (1, 'verified')], default=0)),
                ('profile_is_business_account', models.IntegerField(choices=[(0, 'non-business account'), (1, 'business account')], default=0)),
                ('profile_pic', models.TextField()),
                ('profile_followers', models.IntegerField(default=0)),
                ('profile_followings', models.IntegerField(default=0)),
                ('profile_date', models.DateField(auto_now_add=True)),
                ('profile_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile', to_field='profile_username')),
            ],
            options={
                'ordering': ['-profile_stats_id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_shortcode', models.CharField(max_length=255)),
                ('post_comments_count', models.IntegerField(default=0)),
                ('post_likes_count', models.IntegerField(default=0)),
                ('post_image_category', models.TextField()),
                ('post_er', models.FloatField(default=0.0)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('post_image', models.TextField()),
                ('post_desc', models.TextField()),
                ('profile_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.profile', to_field='profile_username')),
            ],
            options={
                'unique_together': {('post_id', 'profile_username')},
            },
        ),
    ]
