name: Shell commands

on: [push]

jobs: 
  run-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello There"
      - name: multiline script
        run: |
          node -v
          npm -v